openapi: 3.0.0
info:
  title: Reusable components in the health care domain
  version: ${project.version}
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers: []
paths: {}
components:
  schemas:
    NihdiNumber:
      description: Identification number attributed by NIHDI (RIZIV-INAMI) to health care providers in Belgium within the framework of the compulsory health insurance
      type: string
      pattern: '^\d{8}$'
