apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: styleguide-validation
  annotations:
      git-cicd.gcloud.belgium.be/project-slug: rest/styleguide-validation
  links:
    - url: https://git-cicd.gcloud.belgium.be/rest/styleguide-validation
      title: Git Repo
      icon: git
spec:
  type: service
  lifecycle: production
  owner: ICC
