package io.github.belgif.rest.guide.validator.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import io.github.belgif.rest.guide.validator.core.ViolationReport;
import io.github.belgif.rest.guide.validator.core.model.PathDefinition;
global io.github.belgif.rest.guide.validator.core.ViolationReport oas;

function void violationUriExt(ViolationReport oas, PathDefinition path){
        oas.addViolation("[uri-extens]",
                         "The URI SHOULD NOT contain a file extension (A notable exception to this rule is the swagger/OpenAPI file).",
                         path);
}

rule "Uri Extensions V3"
   	when
      $path: PathDefinition(isDirectPath(), $pathUrl: getIdentifier())
      String( this matches(".+\\..+$") ) from $pathUrl
      eval( !$pathUrl.equalsIgnoreCase("/doc/swagger.json") && !$pathUrl.equalsIgnoreCase("/doc/swagger.yaml") &&
            !$pathUrl.equalsIgnoreCase("/doc/openapi.json") && !$pathUrl.equalsIgnoreCase("/doc/openapi.yaml") )
    then
      violationUriExt(oas, $path);
end