package io.github.belgif.rest.guide.validator.rules.oas;

import java.util.Map
import java.util.Set

import org.eclipse.microprofile.openapi.models.security.SecurityScheme;
import org.eclipse.microprofile.openapi.models.security.SecurityScheme.Type;
import org.eclipse.microprofile.openapi.models.security.OAuthFlows;
import org.eclipse.microprofile.openapi.models.security.OAuthFlow;
import org.eclipse.microprofile.openapi.models.security.SecurityRequirement;

import io.github.belgif.rest.guide.validator.core.ViolationReport;
import io.github.belgif.rest.guide.validator.core.ApiFunctions;
import io.github.belgif.rest.guide.validator.core.model.SecurityRequirementDefinition;
import io.github.belgif.rest.guide.validator.core.model.SecuritySchemeDefinition
import java.util.HashSet
import io.github.belgif.rest.guide.validator.core.ViolationLevel;

global io.github.belgif.rest.guide.validator.core.ViolationReport oas;
import io.github.belgif.rest.guide.validator.core.parser.Parser.ParserResult;
global io.github.belgif.rest.guide.validator.core.parser.Parser.ParserResult parserResult;

function void violationScopes(ViolationReport oas, SecurityRequirementDefinition securityRequirementDefinition, String scope, String securitySchemePointer){
    oas.addViolation("[sec-req]", "Scopes defined in a security requirement must also be defined in the referenced security scheme.", "Scope: <<" + scope + ">> not found in: " + securitySchemePointer,
                     securityRequirementDefinition, ViolationLevel.REQUIRED);
}

function void violationSecuritySchemeExists(ViolationReport oas, SecurityRequirementDefinition securityRequirementDefinition, String referencedName){
    oas.addViolation("[sec-req]", "Scopes defined in a security requirement must also be defined in the referenced security scheme.", "Referenced securityScheme: <<" + referencedName + ">> does not exist in entry file.",
                     securityRequirementDefinition, ViolationLevel.REQUIRED);
}

function Set fetchScopesFromFlows(OAuthFlows flows) {
    Set<String> scopes = new HashSet<>();
    if (flows.getImplicit() != null && flows.getImplicit().getScopes() != null) {
      scopes.addAll(flows.getImplicit().getScopes().keySet());
    }
    if (flows.getAuthorizationCode() != null && flows.getAuthorizationCode().getScopes() != null) {
      scopes.addAll(flows.getAuthorizationCode().getScopes().keySet());
    }
    if (flows.getClientCredentials() != null && flows.getClientCredentials().getScopes() != null) {
      scopes.addAll(flows.getClientCredentials().getScopes().keySet());
    }
    return Set.of(scopes);
}

function Set fetchScopesFromSecuritySchemeDefinition(SecuritySchemeDefinition def, ParserResult parserResult) {
    SecuritySchemeDefinition definition = (SecuritySchemeDefinition) parserResult.resolve(def.getModel());
    if (definition.getModel().getFlows() == null) {
      return new HashSet<>();
    }
    return fetchScopesFromFlows(definition.getModel().getFlows());
}

function boolean securitySchemeExistsInEntryDocument(String name, ParserResult parserResult) {
    return parserResult.getSecuritySchemes().stream()
      .anyMatch(def -> def.inEntryDocument() && name.equals(def.getIdentifier()) && ((def.getModel().getType() != null && def.getModel().getType() == Type.OAUTH2) || def.hasReference()));
}

rule "Rule-ScopesAreDefinedInSecurityScheme"
  when
    $securityRequirementDefinition: SecurityRequirementDefinition($schemes: /model/schemes/entrySet, isReachableFromEntryDocument())
    $securitySchemeName: String() from $schemes.getKey()
    $securitySchemeDefinition: SecuritySchemeDefinition(identifier == $securitySchemeName && (model.getType()==Type.OAUTH2 || hasReference()) && inEntryDocument())
    $definedScopes: Set() from fetchScopesFromSecuritySchemeDefinition($securitySchemeDefinition, parserResult)
    $scope: String(!$definedScopes.contains(this)) from $schemes.getValue()
  then
    violationScopes(oas, $securityRequirementDefinition, $scope, $securitySchemeDefinition.getPrintableJsonPointer());
end

rule "Rule-ReferencedSecuritySchemesMustExist"
  when
    $securityRequirementDefinition: SecurityRequirementDefinition($schemes: /model/schemes/entrySet, isReachableFromEntryDocument())
    $securitySchemeName: String(!securitySchemeExistsInEntryDocument(this, parserResult)) from $schemes.getKey()
  then
    violationSecuritySchemeExists(oas, $securityRequirementDefinition, $securitySchemeName);
end