package io.github.belgif.rest.guide.validator.rules.oas;

import org.eclipse.microprofile.openapi.models.PathItem.HttpMethod;
import org.eclipse.microprofile.openapi.models.OpenAPI;
import io.github.belgif.rest.guide.validator.core.ApiFunctions;
import io.github.belgif.rest.guide.validator.core.OpenApiViolationAggregator;
import io.github.belgif.rest.guide.validator.core.model.OperationDefinition;
import org.eclipse.microprofile.openapi.models.Operation;
import org.eclipse.microprofile.openapi.models.responses.APIResponses;
import org.eclipse.microprofile.openapi.models.responses.APIResponse;
import java.util.Set;

global io.github.belgif.rest.guide.validator.core.OpenApiViolationAggregator oas;

function void violationDelete(OpenApiViolationAggregator oas, OperationDefinition operation, String code){
    oas.addViolation("[stat-codes]", "DELETE operation should not have this status code " , "[statuscode: " + code + "]",
                     operation);
}

rule "Delete Status Code 201 v2"
	when
		$operation: OperationDefinition( method == HttpMethod.DELETE )
		OperationDefinition($response: /model/responses/APIResponses[keySet contains "201"]) from $operation
	then
        violationDelete(oas, $operation, "201");
end
rule "Delete Status Code 202 v2"
	when
		$operation: OperationDefinition( method == HttpMethod.DELETE )
		OperationDefinition($response: /model/responses/APIResponses[keySet contains "202"]) from $operation
	then
        violationDelete(oas, $operation, "202");
end
rule "Delete Status Code 304 v2"
	when
		$operation: OperationDefinition( method == HttpMethod.DELETE )
		OperationDefinition($response: /model/responses/APIResponses[keySet contains "304"]) from $operation
	then
        violationDelete(oas, $operation, "304");
end
rule "Delete Status Code 413 v2"
	when
		$operation: OperationDefinition( method == HttpMethod.DELETE )
		OperationDefinition($response: /model/responses/APIResponses[keySet contains "413"]) from $operation
	then
        violationDelete(oas, $operation, "413");
end