package io.github.belgif.rest.guide.validator.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import io.github.belgif.rest.guide.validator.core.ApiFunctions
import io.github.belgif.rest.guide.validator.core.OpenApiViolationAggregator;
global io.github.belgif.rest.guide.validator.core.OpenApiViolationAggregator oas;
import org.eclipse.microprofile.openapi.models.media.Schema;
import org.eclipse.microprofile.openapi.models.media.Schema.SchemaType;
import io.github.belgif.rest.guide.validator.core.model.ExampleDefinition;
import io.github.belgif.rest.guide.validator.core.model.OpenApiDefinition.DefinitionType;
import io.github.belgif.rest.guide.validator.core.util.ExampleValidator;
global io.github.belgif.rest.guide.validator.core.parser.Parser.ParserResult parserResult;

function void violationExamplesShouldValidateAgainstSchema(OpenApiViolationAggregator oas, ExampleDefinition example, String violation){
    oas.addViolation("[oas-exampl]",
    "Example does not validate against schema: <<" + violation + ">>", example);
}

rule "Example should io valid against schema"
    when
//      The validation of examples doesn't work properly for oas2, so is only activated for oas3
        eval(parserResult.getOasVersion() != 2)
        $example: ExampleDefinition(definitionType.equals(DefinitionType.INLINE))
        $violation: String() from ExampleValidator.getExampleViolations($example)
    then
        violationExamplesShouldValidateAgainstSchema(oas, $example, $violation);
end