package io.github.belgif.rest.guide.validator.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import io.github.belgif.rest.guide.validator.core.ApiFunctions
import io.github.belgif.rest.guide.validator.core.ViolationReport;
global io.github.belgif.rest.guide.validator.core.ViolationReport oas;
import org.eclipse.microprofile.openapi.models.media.Schema;
import org.eclipse.microprofile.openapi.models.media.Discriminator;
import org.eclipse.microprofile.openapi.models.media.Schema.SchemaType;
import io.github.belgif.rest.guide.validator.core.model.SchemaDefinition;
import java.util.Set;
import java.util.List;
import java.util.Collection;
import java.util.ArrayList;

function Set excludeCodes() {
  return Set.of("BelgianRegionCode");
}

function void violationCodesShouldBeLowerCamelCase(ViolationReport oas, List<Object> foundCodes, SchemaDefinition schema){
    oas.addViolation("[cod-design]",
    "New code types SHOULD be represented as string values in lowerCamelCase.", "Found: << " + foundCodes + " >>", schema);
}

rule "Codes should be lowerCamelCase"
    when
        $schema: SchemaDefinition($schemaType: /model/type, ApiFunctions.isNotInSet(identifier, excludeCodes()))
        SchemaType( equals(SchemaType.STRING) ) from $schemaType
        Schema( enumeration != null ) from $schema.getModel()
        String(
          ((!this.contains("sort") && !this.contains("Sort")) && !ApiFunctions.isLowerCamelCase($schema.getModel().getEnumeration()))
          || (( this.contains("sort") || this.contains("Sort")) && !ApiFunctions.isLowerCamelCase($schema.getModel().getEnumeration(), "-"))
        ) from $schema.getEffectiveIdentifier()
    then
        violationCodesShouldBeLowerCamelCase(oas, $schema.getModel().getEnumeration(), $schema);
end

rule "Discriminator mappings should be lowerCamelCase"
    when
        $schema: SchemaDefinition(/model/discriminator/mapping != null)
        String(
                  ((!this.contains("sort") && !this.contains("Sort")) && !ApiFunctions.isLowerCamelCase(new ArrayList($schema.getModel().getDiscriminator().getMapping().keySet())))
                  || (( this.contains("sort") || this.contains("Sort")) && !ApiFunctions.isLowerCamelCase(new ArrayList($schema.getModel().getDiscriminator().getMapping().keySet()), "-"))
                ) from $schema.getModel().getDiscriminator().getPropertyName()
    then
        violationCodesShouldBeLowerCamelCase(oas, new ArrayList<Object>($schema.getModel().getDiscriminator().getMapping().keySet()), $schema);
end