package io.github.belgif.rest.guide.validator.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import io.github.belgif.rest.guide.validator.core.ApiFunctions
import io.github.belgif.rest.guide.validator.core.OpenApiViolationAggregator;
global io.github.belgif.rest.guide.validator.core.OpenApiViolationAggregator oas;
import org.eclipse.microprofile.openapi.models.media.Schema;
import org.eclipse.microprofile.openapi.models.media.Schema.SchemaType;
import io.github.belgif.rest.guide.validator.core.model.SchemaDefinition;
import java.util.Set;

function Set excludeCodes() {
  return Set.of("BelgianRegionCode");
}

function void violationCodesShouldBeLowerCamelCase(OpenApiViolationAggregator oas, SchemaDefinition schema){
    oas.addViolation("[cod-design]",
    "New code types SHOULD be represented as string values in lowerCamelCase.", schema);
}

rule "Codes should io lowerCamelCase"
    when
        $schema: SchemaDefinition($schemaType: /model/type)
        SchemaType( equals(SchemaType.STRING) ) from $schemaType
        Schema( getEnumeration() != null ) from $schema.getModel()
        eval(((!$schema.getEffectiveIdentifier().contains("sort") && !$schema.getEffectiveIdentifier().contains("Sort")) && !ApiFunctions.isLowerCamelCase($schema.getModel().getEnumeration()))
        || (( $schema.getEffectiveIdentifier().contains("sort") || $schema.getEffectiveIdentifier().contains("Sort")) && !ApiFunctions.isLowerCamelCase($schema.getModel().getEnumeration(), "-")))
        eval( ApiFunctions.isNotInSet($schema.getIdentifier(), excludeCodes()) )
    then
        violationCodesShouldBeLowerCamelCase(oas, $schema);
end