package io.github.belgif.rest.guide.validator.rules.oas;

import io.github.belgif.rest.guide.validator.core.ViolationReport;
global io.github.belgif.rest.guide.validator.core.ViolationReport oas;
import io.github.belgif.rest.guide.validator.core.model.OpenApiDefinition;
import io.github.belgif.rest.guide.validator.core.model.SchemaDefinition;
import io.github.belgif.rest.guide.validator.core.ViolationLevel;
import org.eclipse.microprofile.openapi.models.Reference;
global io.github.belgif.rest.guide.validator.core.parser.Parser.ParserResult parserResult;
import org.eclipse.microprofile.openapi.models.media.Schema;
import org.eclipse.microprofile.openapi.models.media.Discriminator;

function void violationReferencesShouldPointToTopLevelDefinitions(ViolationReport oas, OpenApiDefinition<?> def, String violatingReference) {
  oas.addViolation("[oas-comp]",
      "A $ref SHOULD reference a definition of the expected type under /components/<definitionTypes>/<componentName>", "Found reference to: <<" + violatingReference + ">>", def, ViolationLevel.RECOMMENDED);
}

function String findReferenceFromComponent(OpenApiDefinition def) {
  return ((Reference<?>) def.getModel()).getRef();
}

rule "References should point to top-level definitions"
    when
        $component: OpenApiDefinition(hasReference())
        OpenApiDefinition(DefinitionType != DefinitionType.TOP_LEVEL) from parserResult.resolve($component.getModel())
    then
        violationReferencesShouldPointToTopLevelDefinitions(oas, $component, ((Reference<?>) $component.getModel()).getRef());
end

rule "Discriminator mappings should point to top-level definitions"
    when
        $schema: SchemaDefinition($mapping: /model/discriminator/mapping/values#String)
        OpenApiDefinition(DefinitionType != DefinitionType.TOP_LEVEL) from parserResult.resolveDiscriminatorMapping($schema, $mapping).get()
    then
        violationReferencesShouldPointToTopLevelDefinitions(oas, $schema, $mapping);
end