package io.github.belgif.rest.guide.validator.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import org.eclipse.microprofile.openapi.models.media.Schema
import org.eclipse.microprofile.openapi.models.media.Schema.SchemaType;
import io.github.belgif.rest.guide.validator.core.ApiFunctions
import io.github.belgif.rest.guide.validator.core.ViolationReport;
import io.github.belgif.rest.guide.validator.core.model.OperationDefinition;
import io.github.belgif.rest.guide.validator.core.model.SchemaDefinition;
import io.github.belgif.rest.guide.validator.core.model.OpenApiDefinition;
import io.github.belgif.rest.guide.validator.core.model.OpenApiDefinition.DefinitionType;
import java.util.List
import java.lang.String

global io.github.belgif.rest.guide.validator.core.ViolationReport oas;

function void violationSummaryShouldBePresentForEachOperation(ViolationReport oas, OperationDefinition operation){
    oas.addViolation("[oas-descr]",
    "The summary property of an operation SHOULD BE present for each operation.",
    operation);
}

function void violationTitleNamesShouldBeUpperCamelCase(ViolationReport oas, String title){
   oas.addViolation("[oas-descr]",
      "Title names SHOULD use UpperCamelCase notation. For abbreviations as well, all letters except the first one should be lowercased.",
      title);
}

function void violationTitleShouldBePresentForInlineObjectSchemas(ViolationReport oas, SchemaDefinition schema){
    oas.addViolation("[oas-descr]",
    "For inline schemas of type 'object' a title MUST BE present.",
    schema);
}

function Boolean isSchemaInAllOrAnyOf(SchemaDefinition schemaDefinition) {
    return schemaDefinition.getJsonPointer().toString().matches("^.*/(all|any)Of/\\d*?$");
}

function void violationTitleShouldNotBePresentOrMatchSchemaName(ViolationReport oas, SchemaDefinition schema,String title){
    oas.addViolation("[oas-descr]",
    "The title property of a component schema MUST NOT be used or MUST MATCH schema name.",
    "'Title << "+ title + " >> found, but schema name was << "+ schema.getIdentifier() +" >>'");
}

function void violationTitleShouldNotBePresentForNonObjectTypesInInlineSchemas(ViolationReport oas, SchemaDefinition schema){
    oas.addViolation("[oas-descr]",
    "The title property of a an inline schema MUST NOT be used for non-object types.",
     schema);
}

rule "A summary should be present for each operation"
  when
    $operation: OperationDefinition(/model[summary == null || summary.trim.empty])
  then
    violationSummaryShouldBePresentForEachOperation(oas, $operation);
end

rule "A title should be present for inline object schemas (not required in an AllOf / AnyOf / Not composition)"
  when
    $schema: SchemaDefinition(
      definitionType == DefinitionType.INLINE,
      /model[type == SchemaType.OBJECT && (title == null || title.trim.empty)],
      !isSchemaInAllOrAnyOf(this)
      )
  then
    violationTitleShouldBePresentForInlineObjectSchemas(oas, $schema);
end

rule "A title names should be UpperCamelCase"
  when
    $schema: SchemaDefinition($title: /model/title#String)
    $title: String(this != null && !this.trim.empty && !ApiFunctions.isUpperCamelCase(this))
  then
    violationTitleNamesShouldBeUpperCamelCase(oas, $title);
end

rule "A title should either be absent or match the component schema name"
    when
        $schema: SchemaDefinition(definitionType == DefinitionType.TOP_LEVEL,
        $title: model.title#String,
        $title != null,
        identifier != $title)
    then
        violationTitleShouldNotBePresentOrMatchSchemaName(oas, $schema, $title);
end

rule "A title property in an inline schema must not be present for non-object types"
    when
        $schema: SchemaDefinition(definitionType == DefinitionType.INLINE,
        /model[title != null && type != SchemaType.OBJECT])
    then
        violationTitleShouldNotBePresentForNonObjectTypesInInlineSchemas(oas, $schema);
end

