package io.github.belgif.rest.guide.validator.rules.oas;

import java.util.Map
import java.util.Set

import org.eclipse.microprofile.openapi.models.security.SecurityScheme;
import org.eclipse.microprofile.openapi.models.security.SecurityScheme.Type;
import org.eclipse.microprofile.openapi.models.security.OAuthFlows;
import org.eclipse.microprofile.openapi.models.security.OAuthFlow;
import org.eclipse.microprofile.openapi.models.security.SecurityRequirement;

import io.github.belgif.rest.guide.validator.core.ViolationReport;
import io.github.belgif.rest.guide.validator.core.ApiFunctions;
import io.github.belgif.rest.guide.validator.core.model.SecurityRequirementDefinition;
import io.github.belgif.rest.guide.validator.core.model.SecuritySchemeDefinition
import java.util.HashSet
import io.github.belgif.rest.guide.validator.core.ViolationLevel;

global io.github.belgif.rest.guide.validator.core.ViolationReport oas;
import io.github.belgif.rest.guide.validator.core.parser.Parser.ParserResult;
global io.github.belgif.rest.guide.validator.core.parser.Parser.ParserResult parserResult;

function void violationScopes(ViolationReport oas, SecurityRequirementDefinition securityRequirementDefinition, String scope, String securitySchemePointer){
    oas.addViolation("[sec-req]", "Scopes defined in a security requirement must also be defined in the referenced security scheme.", "Scope: <<" + scope + ">> not found in: " + securitySchemePointer,
                     securityRequirementDefinition, ViolationLevel.REQUIRED);
}

function Set fetchScopesFromSecuritySchemeDefinition(SecuritySchemeDefinition definition) {
    OAuthFlows flows = definition.getModel().getFlows();
    Set<String> scopes = new HashSet<>();
    if (flows == null) {
      return scopes;
    }
    if (flows.getImplicit() != null && flows.getImplicit().getScopes() != null) {
      scopes.addAll(flows.getImplicit().getScopes().keySet());
    }
    if (flows.getAuthorizationCode() != null && flows.getAuthorizationCode().getScopes() != null) {
      scopes.addAll(flows.getAuthorizationCode().getScopes().keySet());
    }
    if (flows.getClientCredentials() != null && flows.getClientCredentials().getScopes() != null) {
      scopes.addAll(flows.getClientCredentials().getScopes().keySet());
    }
    if (flows.getPassword() != null && flows.getPassword().getScopes() != null) {
      scopes.addAll(flows.getPassword().getScopes().keySet());
    }
    return Set.of(scopes);
}

rule "Rule-ScopesAreDefinedInSecurityScheme"
  when
    $securityRequirementDefinition: SecurityRequirementDefinition($schemes: /model/schemes/entrySet, isReachableFromEntryDocument())
    $securitySchemeName: String() from $schemes.getKey()
    $securitySchemeDefinition: SecuritySchemeDefinition(identifier == $securitySchemeName && inEntryDocument())
    $resolvedSecuritySchemeDefinition: SecuritySchemeDefinition(model.type == Type.OAUTH2 || model.type == Type.OPENIDCONNECT) from parserResult.resolve($securitySchemeDefinition.getModel())
    $definedScopes: Set() from fetchScopesFromSecuritySchemeDefinition($resolvedSecuritySchemeDefinition)
    $scope: String(!$definedScopes.contains(this)) from $schemes.getValue()
  then
    violationScopes(oas, $securityRequirementDefinition, $scope, $resolvedSecuritySchemeDefinition.getPrintableJsonPointer());
end