package io.github.belgif.rest.guide.validator.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import io.github.belgif.rest.guide.validator.core.ViolationReport;
import io.github.belgif.rest.guide.validator.core.model.PathDefinition;
global io.github.belgif.rest.guide.validator.core.ViolationReport oas;

function void violationUriExt(ViolationReport oas, PathDefinition path){
        oas.addViolation("[uri-extens]",
                         "The URI SHOULD NOT contain a file extension (A notable exception to this rule is the OpenAPI file).",
                         path);
}

rule "Uri Extensions V3"
   	when
      $path: PathDefinition(directPath == true, $pathUrl: identifier)
      String( this matches(".+\\..+$") && !this.equalsIgnoreCase("/doc/openapi.json") && !this.equalsIgnoreCase("/doc/openapi.yaml") ) from $pathUrl
    then
      violationUriExt(oas, $path);
end