package io.github.belgif.rest.guide.validator.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import io.github.belgif.rest.guide.validator.core.ApiFunctions
import io.github.belgif.rest.guide.validator.core.OpenApiViolationAggregator
import io.github.belgif.rest.guide.validator.core.ViolationType;
import io.github.belgif.rest.guide.validator.core.model.PathDefinition;
import io.github.belgif.rest.guide.validator.core.model.OperationDefinition;
import org.eclipse.microprofile.openapi.models.PathItem;
global io.github.belgif.rest.guide.validator.core.parser.Parser.ParserResult parserResult;
global io.github.belgif.rest.guide.validator.core.OpenApiViolationAggregator oas;

function void pluralViolation(OpenApiViolationAggregator oas, PathDefinition path){
    oas.addViolation("[col-name]",
           		 "A plural noun SHOULD be used for collection names. ",
           		 path,
           		 ViolationType.RECOMMENDED);
}

rule "Rule-PathInPlural without ID"
    when
        $path: PathDefinition($pathName: getIdentifier(), $operation: /model/GET)
        $operationDefinition: OperationDefinition() from parserResult.resolve($operation)
        eval( ApiFunctions.hasCollectionResponse($operationDefinition, parserResult) || ApiFunctions.existsPathWithPathParamAfter($pathName, parserResult) )
        String( !this.endsWith("}") && !this.endsWith("s") && !this.endsWith("data") && !this.endsWith("Data") && !this.endsWith("/history") ) from $pathName
    then
        pluralViolation(oas, $path);
end