package be.belgium.gcloud.rest.styleguide.validation.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;
import be.belgium.gcloud.rest.styleguide.validation.core.model.OpenApiDefinition;
import be.belgium.gcloud.rest.styleguide.validation.core.model.PathDefinition;
import be.belgium.gcloud.rest.styleguide.validation.core.model.ServerDefinition;


function void violationComponentNamesShouldBeUpperCamelCase(OpenApiViolationAggregator oas, OpenApiDefinition component){
    oas.addViolation("[oas-types]",
    "Component names SHOULD use UpperCamelCase notation. For abbreviations as well, all letters except the first one should be lowercased.", component);
}

rule "Component names should be UpperCamelCase"
    when
        $component: OpenApiDefinition(definitionType == DefinitionType.TOP_LEVEL, $jsonPointer: jsonPointer.toPrettyString(), $componentName: identifier)
        String( startsWith("/components") ) from $jsonPointer
        eval( !ApiFunctions.isUpperCamelCase($componentName) )
    then
        violationComponentNamesShouldBeUpperCamelCase(oas, $component);
end