package be.belgium.gcloud.rest.styleguide.validation.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions;
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
import be.belgium.gcloud.rest.styleguide.validation.core.model.SchemaDefinition;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;

function void violationPropertiesCamelCase(OpenApiViolationAggregator oas, String propertyName, SchemaDefinition schema){
    oas.addViolation("[jsn-naming]",
           		 "All JSON property names SHOULD be written in lowerCamelCase notation. \t" +
           		    "[propertyName: " + propertyName + "]",
           		  schema);
}

rule "Properties CamelCase"
	when
        $schema: SchemaDefinition($propertyName: /model/properties/keySet#String)
        eval( !ApiFunctions.isLowerCamelCase($propertyName) )
    then
        violationPropertiesCamelCase(oas, $propertyName, $schema);
end
