package be.belgium.gcloud.rest.styleguide.validation.rules.oas;

import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions;
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;
import org.eclipse.microprofile.openapi.models.media.Schema.SchemaType;
import java.util.Set;
global be.belgium.gcloud.rest.styleguide.validation.core.parser.Parser.ParserResult parserResult;
import be.belgium.gcloud.rest.styleguide.validation.core.model.MediaTypeDefinition;
import be.belgium.gcloud.rest.styleguide.validation.core.model.SchemaDefinition;


function Set includeContentTypes() {
  return Set.of("application/json", "multipart/*");
}

function void violationJsonObjectAsTopLevelStructure(OpenApiViolationAggregator oas, MediaTypeDefinition mediaTypeDefinition){
  oas.addViolation("[evo-object]",
    "In a request or response body, if any, you MUST always return a JSON object (and not e.g. an array) as a top level data structure to support future extensibility. ",
    mediaTypeDefinition);
}

rule "[evo-object] JSON object as top level structure"
  when
    $mediaTypeDefinition: MediaTypeDefinition()
    eval(ApiFunctions.isMediaTypeIncluded($mediaTypeDefinition.getIdentifier(), includeContentTypes()))
    MediaTypeDefinition($schema: /model/schema) from $mediaTypeDefinition
    eval( ApiFunctions.isSchemaOfType($schema, SchemaType.OBJECT, parserResult) == false )
  then
    violationJsonObjectAsTopLevelStructure(oas, $mediaTypeDefinition);
end
