package be.belgium.gcloud.rest.styleguide.validation.rules.oas;

import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions
import be.belgium.gcloud.rest.styleguide.validation.core.model.ServerDefinition;
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;
global be.belgium.gcloud.rest.styleguide.validation.core.parser.Parser.ParserResult parserResult;


function String urlPattern(){
    return "^((http://localhost)[:0-9]{0,7}/?|(https://[-a-zA-Z0-9@:%._\\+~#=]{1,256})|/?)(/[A-Za-z0-9]*)*(/[a-z0-9]+([A-Z]?[a-z0-9]+)*)+/v[0-9]+$";
}

function void violationServerUrlFormat(OpenApiViolationAggregator oas, ServerDefinition server){
    oas.addViolation("[uri-format]",
                     "The server url should follow the format [/pathPrefix]/apiName/vMajorVersion optionally prefixed by https://hostname[:port] or http://localhost[:port]. The apiName must consist of one or more path segments in lowerCamelCase.",
                     server);
}

rule "Server Url or basePath Format"
    when
        eval( !parserResult.getPathDefinitions().isEmpty() )
        $server: ServerDefinition($url: /model/url)
        not String( this matches(urlPattern()) ) from $url
    then
        violationServerUrlFormat(oas, $server);
end