package be.belgium.gcloud.rest.styleguide.validation.rules.oas;

import org.eclipse.microprofile.openapi.models.PathItem.HttpMethod;
import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions;
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
import be.belgium.gcloud.rest.styleguide.validation.core.model.OperationDefinition;
import org.eclipse.microprofile.openapi.models.Operation;
import org.eclipse.microprofile.openapi.models.responses.APIResponses;
import org.eclipse.microprofile.openapi.models.responses.APIResponse;
import java.util.Set;

global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;

function void violationPatch(OpenApiViolationAggregator oas, OperationDefinition operation, String code){
    oas.addViolation("[stat-codes]", "PATCH operation should not have a status code: "+code,
                     operation);
}

rule "Patch Status Code 201 v3"
	when
		$operation: OperationDefinition( method == HttpMethod.PATCH)
		OperationDefinition($response: /model/responses/APIResponses[keySet contains "201"]) from $operation
	then
        violationPatch(oas, $operation, "201");
end
rule "Patch Status Code 202 v3"
	when
		$operation: OperationDefinition( method == HttpMethod.PATCH)
		OperationDefinition($response: /model/responses/APIResponses[keySet contains "202"]) from $operation
	then
        violationPatch(oas, $operation, "202");
end
rule "Patch Status Code 304 v3"
	when
		$operation: OperationDefinition( method == HttpMethod.PATCH)
		OperationDefinition($response: /model/responses/APIResponses[keySet contains "304"]) from $operation
	then
        violationPatch(oas, $operation, "304");
end