package be.belgium.gcloud.rest.styleguide.validation.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;
import java.util.Set;
import java.util.List;
import be.belgium.gcloud.rest.styleguide.validation.core.model.ParameterDefinition;
import be.belgium.gcloud.rest.styleguide.validation.core.model.PathDefinition;
import org.eclipse.microprofile.openapi.models.parameters.Parameter;
import org.eclipse.microprofile.openapi.models.parameters.Parameter.In;

function void violationPath(OpenApiViolationAggregator oas, PathDefinition path){
    oas.addViolation("[uri-notat]",
           		 "The URI notation MUST use lowerCamelCase to enhance readability and to separate compound names. ",
           		 path);
}

function void violationPathParam(OpenApiViolationAggregator oas, ParameterDefinition parameterDefinition){
  oas.addViolation("[uri-notat]",
    "The URI notation MUST use lowerCamelCase to enhance readability and to separate compound names. ",
    parameterDefinition);
}

rule "Path CamelCase"
	when
        $path: PathDefinition( $pathString: getIdentifier() )
        String(!this.endsWith("/doc/swagger.json") && !this.endsWith("/doc/swagger.yaml") && !this.endsWith("/doc/openapi.json") && !this.endsWith("/doc/openapi.yaml")) from $pathString
        String($pathSegmentList: this.split("/")) from $pathString
        $pathSegment: String( !this.equals("") && !this.startsWith("{") && !this.endsWith("}")) from $pathSegmentList
        eval( !ApiFunctions.isLowerCamelCase($pathSegment) )
    then
        violationPath(oas, $path);
end

rule "Path Parameter CamelCase"
  when
    $parameterDefinition: ParameterDefinition(getModel().getIn().equals(In.PATH))
    ParameterDefinition($parameterName: /model/name) from $parameterDefinition
    eval( !ApiFunctions.isLowerCamelCase($parameterName) )
  then
    violationPathParam(oas, $parameterDefinition);
end

rule "Query Parameter lowerCamelCase with extra characters"
  when
    $parameterDefinition: ParameterDefinition(getModel().getIn().equals(In.QUERY))
    ParameterDefinition($parameterName: /model/name) from $parameterDefinition
    eval( !ApiFunctions.isLowerCamelCase($parameterName, List.of(".", "_")) )
  then
    violationPathParam(oas, $parameterDefinition);
end
