package be.belgium.gcloud.rest.styleguide.validation.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator
import be.belgium.gcloud.rest.styleguide.validation.core.ViolationType;
import be.belgium.gcloud.rest.styleguide.validation.core.model.PathDefinition;
import be.belgium.gcloud.rest.styleguide.validation.core.model.OperationDefinition;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;
global be.belgium.gcloud.rest.styleguide.validation.core.parser.Parser.ParserResult parserResult;
import org.eclipse.microprofile.openapi.models.PathItem;
import org.eclipse.microprofile.openapi.models.Operation;

function void representationOfCollectionViolation(OpenApiViolationAggregator oas, OperationDefinition operation){
    oas.addViolation("[col-repres]",
           		 "A query on a collection MUST contain an items property with an array of objects, each one representing an item in the collection. \t",
           		 operation);
}

rule "Rule-Representation Of Collection"
    when
       $path: PathDefinition($operation: /model/GET)
       $operationDefinition: OperationDefinition() from parserResult.resolve($operation)
       eval( ApiFunctions.existsPathWithPathParamAfter($path.getIdentifier(), parserResult) )
       eval( !ApiFunctions.hasCollectionResponse($operationDefinition, parserResult))
    then
        representationOfCollectionViolation(oas, $operationDefinition);
end