package be.belgium.gcloud.rest.styleguide.validation.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import org.eclipse.microprofile.openapi.models.media.Schema;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions;
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
import be.belgium.gcloud.rest.styleguide.validation.core.model.SchemaDefinition;
import be.belgium.gcloud.rest.styleguide.validation.core.model.OpenApiDefinition;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;
global be.belgium.gcloud.rest.styleguide.validation.core.parser.Parser.ParserResult parserResult;
import java.util.Map
import be.belgium.gcloud.rest.styleguide.validation.core.parser.Parser;

function void violationRequiredProperties(OpenApiViolationAggregator oas, SchemaDefinition schema, String requiredValue){
    oas.addViolation("[propertyReq]",
        "Value <<"+ requiredValue + ">> is in the required list of a schema but is not defined as a property",
        schema);
}

rule "Values of required should be defined as properties"
    when
        $schema: SchemaDefinition(isHighLevelSchema())
        $required: String() from ApiFunctions.getRequiredValues($schema, parserResult)
        not Map( containsKey($required) ) from ApiFunctions.getRecursiveProperties($schema.getModel(), parserResult)
    then
        violationRequiredProperties(oas, $schema, $required);
end