package be.belgium.gcloud.rest.styleguide.validation.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;
import be.belgium.gcloud.rest.styleguide.validation.core.model.SchemaDefinition;


function void violationTitleShouldNotBeSet(OpenApiViolationAggregator oas, SchemaDefinition schema){
    oas.addViolation("[oas-descr]",
    "The title property of a Schema MUST NOT be used.", schema);
}

rule "Title property of a schema must not be set"
    when
        $schema: SchemaDefinition(/model[title != null])
    then
        violationTitleShouldNotBeSet(oas, $schema);
end