package be.belgium.gcloud.rest.styleguide.validation.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;
import org.eclipse.microprofile.openapi.models.media.Schema;
import org.eclipse.microprofile.openapi.models.media.Schema.SchemaType;
import be.belgium.gcloud.rest.styleguide.validation.core.model.SchemaDefinition;
import java.util.Set;

function Set excludeCodes() {
  return Set.of("BelgianRegionCode");
}

function void violationCodesShouldBeLowerCamelCase(OpenApiViolationAggregator oas, SchemaDefinition schema){
    oas.addViolation("[cod-design]",
    "New code types SHOULD be represented as string values in lowerCamelCase.", schema);
}

rule "Codes should be lowerCamelCase"
    when
        $schema: SchemaDefinition($schemaType: /model/type)
        SchemaType( equals(SchemaType.STRING) ) from $schemaType
        Schema( getEnumeration() != null ) from $schema.getModel()
        eval(((!$schema.getEffectiveIdentifier().contains("sort") && !$schema.getEffectiveIdentifier().contains("Sort")) && !ApiFunctions.isLowerCamelCase($schema.getModel().getEnumeration()))
        || (( $schema.getEffectiveIdentifier().contains("sort") || $schema.getEffectiveIdentifier().contains("Sort")) && !ApiFunctions.isLowerCamelCase($schema.getModel().getEnumeration(), "-")))
        eval( ApiFunctions.isNotInSet($schema.getIdentifier(), excludeCodes()) )
    then
        violationCodesShouldBeLowerCamelCase(oas, $schema);
end