package be.belgium.gcloud.rest.styleguide.validation.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import org.eclipse.microprofile.openapi.models.media.Schema;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions;
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
import be.belgium.gcloud.rest.styleguide.validation.core.model.SchemaDefinition;
import be.belgium.gcloud.rest.styleguide.validation.core.model.OpenApiDefinition;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;
global be.belgium.gcloud.rest.styleguide.validation.core.parser.Parser.ParserResult parserResult;
import java.util.Map
import be.belgium.gcloud.rest.styleguide.validation.core.parser.Parser;

function void violationReadOnlyProperties(OpenApiViolationAggregator oas, SchemaDefinition schema, String propertyName){
    oas.addViolation("[oas-rdonly]",
        "Properties marked as readOnly being true SHOULD NOT be in the required list of the defined schema. [readOnly property: " + propertyName + "] \t",
        schema);
}

rule "ReadOnly Properties"
    when
        $schema: SchemaDefinition()
        Map($property: /entrySet) from ApiFunctions.getRecursiveProperties($schema.getModel(), parserResult)
        $propertyKey: String() from $property.getKey()
        eval ( ApiFunctions.isPropertyRequiredAndReadOnly($schema, $propertyKey, parserResult) )
    then
        violationReadOnlyProperties(oas, $schema, $propertyKey);
end