package be.belgium.gcloud.rest.styleguide.validation.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
import be.belgium.gcloud.rest.styleguide.validation.core.model.PathDefinition;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;

function void violationUriExt(OpenApiViolationAggregator oas, PathDefinition path){
        oas.addViolation("[uri-extens]",
                         "The URI SHOULD NOT contain a file extension (A notable exception to this rule is the swagger/OpenAPI file). \t",
                         path);
}

rule "Uri Extensions V3"
   	when
      $path: PathDefinition($pathUrl: getIdentifier())
      String( this matches(".+\\..+$") ) from $pathUrl
      eval( !$pathUrl.equalsIgnoreCase("/doc/swagger.json") && !$pathUrl.equalsIgnoreCase("/doc/swagger.yaml") &&
            !$pathUrl.equalsIgnoreCase("/doc/openapi.json") && !$pathUrl.equalsIgnoreCase("/doc/openapi.yaml") )
    then
      violationUriExt(oas, $path);
end