package be.belgium.gcloud.rest.styleguide.validation.rules.oas;

import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions
import be.belgium.gcloud.rest.styleguide.validation.core.model.ServerDefinition;
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;


function String urlPattern(){
    return "^((http://localhost/?)|(https://)|/?)[-a-zA-Z0-9@:%._\\+~#=]{1,256}[a-zA-Z0-9()]{1,6}(/[A-Za-z0-9]*)*(/[a-z0-9]+([A-Z]?[a-z0-9]+)*)*/v[0-9]+$";
}

function void violationServerUrlFormat(OpenApiViolationAggregator oas, ServerDefinition server){
    oas.addViolation("[uri-format]",
                     "The server url (or the basePath) should follow this format: host/[pathPrefix]/apiName/vmajorVersion. The path segments must be written in lowerCamelCase. BAD: ",
                     server);
}

function void violationServerSecuredUrl(OpenApiViolationAggregator oas, ServerDefinition server){
    oas.addViolation("serverUrlFormat",
                     "The server url (or the basePath) should be at least secured on transport level using a one-way TLS connection.",
                     server);
}

rule "Server Url or basePath Format"
    when
		$server: ServerDefinition($url: /model/url)
		not String( this matches(urlPattern()) ) from $url
    then
        violationServerUrlFormat(oas, $server);
end

rule "Secured Server Url or secured basePath"
    when
		$server: ServerDefinition($url: /model/url)
		not String( this matches("^(http://localhost|https://|/?).*") ) from $url
    then
        violationServerSecuredUrl(oas, $server);
end
