package be.belgium.gcloud.rest.styleguide.validation.rules.oas;

import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;
import java.util.Set;
import be.belgium.gcloud.rest.styleguide.validation.core.model.ParameterDefinition;
import be.belgium.gcloud.rest.styleguide.validation.core.model.ResponseDefinition;
import org.eclipse.microprofile.openapi.models.parameters.Parameter;
import org.eclipse.microprofile.openapi.models.parameters.Parameter.In
import be.belgium.gcloud.rest.styleguide.validation.core.parser.Parser;

function void violationRequestHeaderParam(OpenApiViolationAggregator oas, ParameterDefinition parameterDefinition){
  oas.addViolation("[hdr-case]",
    "By convention, HTTP headers SHOULD use Kebab-Case with uppercase for readability and consistency. ",
    parameterDefinition);
}

function void violationResponseHeaderParam(OpenApiViolationAggregator oas, ResponseDefinition headerDefinition, String headerName){
  oas.addViolation("[hdr-case]",
    "By convention, HTTP headers SHOULD use Kebab-Case with uppercase for readability and consistency. ["+headerName+"]",
    headerDefinition);
}

rule "RequestHeader parameter should be Upper-Kebab-Case"
  when
    $parameterDefinition: ParameterDefinition(getModel().getIn().equals(In.HEADER))
    ParameterDefinition($parameterName: /model/name) from $parameterDefinition
    eval( !ApiFunctions.isUpperKebabCase($parameterName) )
  then
    violationRequestHeaderParam(oas, $parameterDefinition);
end

rule "ResponseHeader should be Upper-Kebab-Case"
  when
    $response: ResponseDefinition($headerName: /model/headers/keySet#String)
    eval( !ApiFunctions.isUpperKebabCase($headerName) )
  then
    violationResponseHeaderParam(oas, $response, $headerName);
end
