openapi: 3.0.0
info:
  title: cloud events testcase
  description: description
  version: v1
servers:
  - url: /demo/v1
paths: {}
components:
  schemas:
    ExtraSchema:
      type: object
      properties:
        first:
          type: string
        second:
          type: string
        third:
          type: string
          nullable: true
        type:
          type: string
          enum:
            - something.like.this
            - or.something.completely.different
    CorrectSchema:
      allOf:
        - $ref: '#/components/schemas/ExtraSchema'
        - $ref: './schemas/cloudevents/v1/cloudevents-v1.yaml#/components/schemas/AsynchronousMessageBase'
    SchemaOne:
      allOf:
        - $ref: '#/components/schemas/ExtraSchema'
      properties:
        extra:
          type: string
    SchemaTwo:
      allOf:
        - $ref: '#/components/schemas/ExtraSchema'
      properties:
        extraTwo:
          type: string
    OneOfSchema:
      oneOf:
        - $ref: '#/components/schemas/SchemaOne'
        - $ref: '#/components/schemas/SchemaTwo'
      discriminator:
        propertyName: type
        mapping:
          something.like.this: '#/components/schemas/SchemaOne'
          or.something.completely.different: '#/components/schemas/SchemaTwo'
    WrongSchema:
      allOf:
        - $ref: '#/components/schemas/ExtraSchema'
      properties:
        somethingExtra:
          type: number
security:
  - {}