package be.belgium.gcloud.rest.styleguide.validation.core.rules.oas2;

import java.util.List;
import org.eclipse.microprofile.openapi.models.PathItem.HttpMethod;
import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions;
import be.belgium.gcloud.rest.styleguide.validation.core.jsonpath.ApiPathFunctions;
import be.belgium.gcloud.rest.styleguide.validation.core.jsonpath.OperationData;
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;
global java.lang.String jsonString;

function void violationProduce(OpenApiViolationAggregator oas, String operation, String operationId){
    oas.addViolation("[med-types]",
     "OpenAPI 2.0 specifications SHOULD specify following default media types for produces: 'application/json' and 'application/problem+json'. \t"+ operationId + " ("+operation+")",
      oas.getLineNumber(operationId));
}
function void violationConsume(OpenApiViolationAggregator oas, String operation, String operationId){
    oas.addViolation("[med-types]",
     "OpenAPI 2.0 specifications SHOULD specify following default media types for consumes: 'application/json'. \t"+ operationId + " ("+operation+")",
      oas.getLineNumber(operationId));
}
//TODO: Should be refactored
// produces
rule "Rule-defaultMediaType-getDontHaveProduces"
    when
        $api: OpenAPI()
        $operationId: String() from ApiPathFunctions.operationIdDontHaveProduce(jsonString, HttpMethod.GET)
    then
        violationProduce(oas,HttpMethod.GET.name(), $operationId);
end

rule "Rule-defaultMediaType-getDontHaveCorrectProduces"
    when
        $api: OpenAPI()
        $operationData: OperationData() from ApiPathFunctions.operationDataDontHaveProduce(jsonString, HttpMethod.GET, ApiPathFunctions.PRODUCES_MEDIATYPE)
    then
        violationProduce(oas, HttpMethod.GET.name(), $operationData.getOperationId());
end

rule "Rule-defaultMediaType-posttDontHaveCorrectProduces"
    when
        $api: OpenAPI()
        $operationData: OperationData() from ApiPathFunctions.operationDataDontHaveProduce(jsonString, HttpMethod.POST, ApiPathFunctions.PRODUCES_MEDIATYPE)
    then
        violationProduce(oas, HttpMethod.POST.name(), $operationData.getOperationId());
end

rule "Rule-defaultMediaType-putDontHaveCorrectProduces"
    when
        $api: OpenAPI()
        $operationData: OperationData() from ApiPathFunctions.operationDataDontHaveProduce(jsonString, HttpMethod.PUT, ApiPathFunctions.PRODUCES_MEDIATYPE)
    then
        violationProduce(oas, HttpMethod.PUT.name(), $operationData.getOperationId());
end

rule "Rule-defaultMediaType-patchDontHaveCorrectProduces"
    when
        $api: OpenAPI()
        $operationData: OperationData() from ApiPathFunctions.operationDataDontHaveProduce(jsonString, HttpMethod.PATCH, ApiPathFunctions.PRODUCES_MEDIATYPE)
    then
        violationProduce(oas, HttpMethod.PATCH.name(), $operationData.getOperationId());
end

rule "Rule-defaultMediaType-optionsDontHaveCorrectProduces"
    when
        $api: OpenAPI()
        $operationData: OperationData() from ApiPathFunctions.operationDataDontHaveProduce(jsonString, HttpMethod.OPTIONS, ApiPathFunctions.PRODUCES_MEDIATYPE)
    then
        violationProduce(oas, HttpMethod.OPTIONS.name(), $operationData.getOperationId());
end

// consumes
rule "Rule-defaultMediaType-postDontHaveConsumes"
    when
        $api: OpenAPI()
        $operationId: String() from ApiPathFunctions.operationIdDontHaveConsume(jsonString, HttpMethod.POST)
    then
        violationConsume(oas, HttpMethod.POST.name(), $operationId);
end
rule "Rule-defaultMediaType-postDontHaveCorrectConsumes"
    when
        $api: OpenAPI()
        $operationData: OperationData() from ApiPathFunctions.operationDataDontHaveConsume(jsonString, HttpMethod.POST, ApiPathFunctions.CONSUMES_MEDIATYPE)
    then
        violationConsume(oas, HttpMethod.POST.name(), $operationData.getOperationId());
end

rule "Rule-defaultMediaType-putDontHaveConsumes"
    when
        $api: OpenAPI()
        $operationId: String() from ApiPathFunctions.operationIdDontHaveConsume(jsonString, HttpMethod.PUT)
    then
        violationConsume(oas, HttpMethod.PUT.name(), $operationId);
end
rule "Rule-defaultMediaType-putDontHaveCorrectConsumes"
    when
        $api: OpenAPI()
        $operationData: OperationData() from ApiPathFunctions.operationDataDontHaveConsume(jsonString, HttpMethod.PUT, ApiPathFunctions.CONSUMES_MEDIATYPE)
    then
        violationConsume(oas, HttpMethod.PUT.name(), $operationData.getOperationId());
end

rule "Rule-defaultMediaType-patchDontHaveConsumes"
    when
        $api: OpenAPI()
        $operationId: String() from ApiPathFunctions.operationIdDontHaveConsume(jsonString, HttpMethod.PATCH)
    then
        violationConsume(oas, HttpMethod.PATCH.name(), $operationId);
end
rule "Rule-defaultMediaType-patchDontHaveCorrectConsumes"
    when
        $api: OpenAPI()
        $operationData: OperationData() from ApiPathFunctions.operationDataDontHaveConsume(jsonString, HttpMethod.PATCH, ApiPathFunctions.CONSUMES_MEDIATYPE)
    then
        violationConsume(oas, HttpMethod.PATCH.name(), $operationData.getOperationId());
end