openapi: 3.0.0
info:
  title: REST reference implementation
  description: This is the reference implementation of a REST API following the G-Cloud style guide.
  version: v1
tags:
  - name: ReferenceData
  - name: Organization
  - name: Employer
  - name: Logos
  - name: Documentation
  - name: Monitoring
servers:
  - url: /demo/v1
paths:
  /refData/employerClasses:
    get:
      tags:
        - ReferenceData
      summary: Get the complete reference data list of employer classes
      operationId: getEmployerClasses
      parameters:
        - name: Accept-Language
          in: header
          description: User language
          required: false
          schema:
            x-ignore-rules:
              "cod-design": this rule will be ignored
            type: string
            enum:
              - NL
              - fr
        - name: Another-Header
          in: header
          schema:
            type: string
            enum:
              - MY_FIRST_THING
              - second
      responses:
        default:
          description: Yes
          content:
            application/json:
              schema:
                type: string