package io.github.belgif.rest.styleguide.validation.rules.oas;

import io.github.belgif.rest.styleguide.validation.core.ApiFunctions;
import io.github.belgif.rest.styleguide.validation.core.OpenApiViolationAggregator
import org.eclipse.microprofile.openapi.models.PathItem.HttpMethod;
import io.github.belgif.rest.styleguide.validation.core.model.OperationDefinition;
global io.github.belgif.rest.styleguide.validation.core.OpenApiViolationAggregator oas;
import io.github.belgif.rest.styleguide.validation.core.model.ResponseDefinition;
global io.github.belgif.rest.styleguide.validation.core.parser.Parser.ParserResult parserResult;

function void violationNoDefaultResponse(OpenApiViolationAggregator oas, OperationDefinition operation){
  oas.addViolation("[prb-defaul]",
    "A default Problem response SHOULD be added to each operation with media type \"application/problem+json\" \t" +
    "[Operation: " + operation.getIdentifier() + "]",
    operation);
}

rule "Default Response is missing"
  when
    $operationDefinition: OperationDefinition(method != HttpMethod.HEAD && method != HttpMethod.OPTIONS)
    OperationDefinition(/model/responses[defaultValue == null]) from $operationDefinition
  then
    violationNoDefaultResponse(oas, $operationDefinition);
end