package io.github.belgif.rest.styleguide.validation.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import io.github.belgif.rest.styleguide.validation.core.ApiFunctions
import io.github.belgif.rest.styleguide.validation.core.OpenApiViolationAggregator;
global io.github.belgif.rest.styleguide.validation.core.OpenApiViolationAggregator oas;
import io.github.belgif.rest.styleguide.validation.core.model.OpenApiDefinition;
import io.github.belgif.rest.styleguide.validation.core.model.PathDefinition;
import io.github.belgif.rest.styleguide.validation.core.model.ServerDefinition;


function void violationComponentNamesShouldBeUpperCamelCase(OpenApiViolationAggregator oas, OpenApiDefinition component){
    oas.addViolation("[oas-comp]",
    "Component names SHOULD use UpperCamelCase notation. For abbreviations as well, all letters except the first one should be lowercased.", component);
}

rule "Component names should io UpperCamelCase"
    when
        $component: OpenApiDefinition(definitionType == DefinitionType.TOP_LEVEL, $jsonPointer: jsonPointer.toPrettyString(), $componentName: identifier)
        String( startsWith("/components") ) from $jsonPointer
        eval( !ApiFunctions.isUpperCamelCase($componentName) )
    then
        violationComponentNamesShouldBeUpperCamelCase(oas, $component);
end