package be.belgium.gcloud.rest.styleguide.validation.core.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions;
import be.belgium.gcloud.rest.styleguide.validation.core.ComponentProperties;
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;

function String patternCamelCase(){
    return "^[a-z]+([A-Z]?[a-z0-9]+)*$" ;
}
function void violationPropertiesCamelCase(OpenApiViolationAggregator oas, ComponentProperties property){
    oas.addViolation("[jsn-naming]",
           		 "All JSON property names must be in American English and must be written in lowerCamelCase notation. \t" +
           		    "[" + property.getType() + "]" + property.getPropertyKey() + ":" + property.getPropertyName(),
           		  oas.getLineNumber(oas.getLineNumber(property.getPropertyKey()),property.getPropertyName()));
}

rule "Path Properties CamelCase"
	when
        $api: OpenAPI()
        $property: ComponentProperties() from ApiFunctions.getPropertiesNotMatch($api, patternCamelCase())
    then
        violationPropertiesCamelCase(oas, $property);
end
