package be.belgium.gcloud.rest.styleguide.validation.core.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions;
import be.belgium.gcloud.rest.styleguide.validation.core.PropertyDefinition;
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator
import org.eclipse.microprofile.openapi.models.PathItem.HttpMethod;
import org.eclipse.microprofile.openapi.models.Operation;
import org.eclipse.microprofile.openapi.models.responses.APIResponses;
import org.eclipse.microprofile.openapi.models.responses.APIResponse;
import org.eclipse.microprofile.openapi.models.media.Content;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;
import java.util.Set;


function Set exclude() {
  return Set.of(HttpMethod.HEAD, HttpMethod.OPTIONS);
}

function void violationDefaultResponse(OpenApiViolationAggregator oas, String property){
  oas.addViolation("[prb-defaul]",
    "A default Problem response SHOULD be added to each operation with media type \"application/problem+json\" \t" +
    "[Operation: " + property + "]",
    oas.getLineNumber(property));
}

rule "Default Response with problem+json media type is missing"
  when
    $api: OpenAPI()
    $operation: Operation($operationId : operationId) from ApiFunctions.getOperations($api, exclude())
    not(Operation(responses!.defaultValue!.content!.mediaTypes!.keySet contains "application/problem+json") from $operation)

  then
    violationDefaultResponse(oas, $operationId);
end