package be.belgium.gcloud.rest.styleguide.validation.core.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions;
import be.belgium.gcloud.rest.styleguide.validation.core.PropertyDefinition;
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;

function void violationPropertiesCamelCase(OpenApiViolationAggregator oas, PropertyDefinition property){
    oas.addViolation("[jsn-naming]",
           		 "All JSON property names must be in American English and must be written in lowerCamelCase notation. \t" +
           		    "[" + property.getParentDefinitionLocation() + "]" + property.getParentName() + ":" + property.getPropertyName(),
           		  oas.getLineNumber(oas.getLineNumber(property.getParentName()),property.getPropertyName()));
}

rule "Properties CamelCase"
	when
        $api: OpenAPI()
        $property: PropertyDefinition( $propertyName: propertyName ) from ApiFunctions.getProperties($api)
        Boolean( this == false ) from ApiFunctions.isLowerCamelCase($propertyName)
    then
        violationPropertiesCamelCase(oas, $property);
end
