package be.belgium.gcloud.rest.styleguide.validation.core.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;
import org.eclipse.microprofile.openapi.models.media.Schema;
import org.eclipse.microprofile.openapi.models.media.Schema.SchemaType;
import be.belgium.gcloud.rest.styleguide.validation.core.SchemaDefinition;

function void violationCodesShouldBeLowerCamelCase(OpenApiViolationAggregator oas, SchemaDefinition schema){
    oas.addViolation("[cod-design]",
    "New code types SHOULD be represented as string values in lowerCamelCase. \t"+ schema.getParentName() + "." + schema.getSchema().getEnumeration(),
    oas.getLineNumber(schema.getParentName()));
}

rule "Codes should be lowerCamelCase"
	when
        $api: OpenAPI()
        $schema: SchemaDefinition() from ApiFunctions.getSchemas($api)
        not String( this.equals("BelgianRegionCode") ) from $schema.getParentName()
        SchemaType( equals(SchemaType.STRING) ) from $schema.getSchema().getType()
        $code: String() from $schema.getSchema().getEnumeration()
        Boolean( this == false ) from ApiFunctions.isLowerCamelCase($code)
    then
        violationCodesShouldBeLowerCamelCase(oas, $schema);
end
