package be.belgium.gcloud.rest.styleguide.validation.core.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;
import java.util.Set;
import be.belgium.gcloud.rest.styleguide.validation.core.model.ParameterDefinition;
import org.eclipse.microprofile.openapi.models.parameters.Parameter;
import org.eclipse.microprofile.openapi.models.parameters.Parameter.In;

function void violationPath(OpenApiViolationAggregator oas, String path){
    oas.addViolation("[uri-notat]",
           		 "The URI notation MUST use lowerCamelCase to enhance readability and to separate compound names. \t"+ path,
           		 oas.getLineNumber(path));
}

function void violationPathParam(OpenApiViolationAggregator oas, ParameterDefinition parameterDefinition){
  oas.addViolation("[uri-notat]",
    "The URI notation MUST use lowerCamelCase to enhance readability and to separate compound names. ",
    parameterDefinition);
}

rule "Path CamelCase"
	when
        $api: OpenAPI($path: /paths/pathItems/keySet#String)
        String(!this.endsWith("/doc/swagger.json") && !this.endsWith("/doc/swagger.yaml") && !this.endsWith("/doc/openapi.json") && !this.endsWith("/doc/openapi.yaml")) from $path
        String($pathSegmentList: this.split("/")) from $path
        $pathSegment: String( !this.equals("") && !this.startsWith("{") && !this.endsWith("}")) from $pathSegmentList
        eval( !ApiFunctions.isLowerCamelCase($pathSegment) )
    then
        violationPath(oas, $path);
end

rule "Path Parameter CamelCase"
  when
    $parameterDefinition: ParameterDefinition(getModel().getIn().equals(In.PATH))
    ParameterDefinition($parameterName: /model/name) from $parameterDefinition
    eval( !ApiFunctions.isLowerCamelCase($parameterName) )
  then
    violationPathParam(oas, $parameterDefinition);
end
