package be.belgium.gcloud.rest.styleguide.validation.core.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator
import be.belgium.gcloud.rest.styleguide.validation.core.ViolationType;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;

function void pluralViolation(OpenApiViolationAggregator oas, String path){
    oas.addViolation("[col-name]",
           		 "A plural noun SHOULD be used for collection names. \t"+ path,
           		 oas.getLineNumber(path),
           		 ViolationType.RECOMMENDED);
}

rule "Rule-PathInPlural without ID"
    when
       $api: OpenAPI()
       $path: String() from ApiFunctions.getReturnCollectionPathKey($api)
    then
      if( !  $path.endsWith("}") && ! $path.endsWith("s"))
        pluralViolation(oas, $path);
end

rule "Rule-PathInPlural with ID"
    when
       $api: OpenAPI()
       $path: String() from ApiFunctions.getReturnCollectionPathKey($api)

       String( endsWith("}") ) from $path
       String( $parts : split("/") ) from $path
       not String ( endsWith("s") ) from $parts
    then
       pluralViolation(oas, $path);
end
