package be.belgium.gcloud.rest.styleguide.validation.core.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions;
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator
import org.eclipse.microprofile.openapi.models.PathItem.HttpMethod;
import org.eclipse.microprofile.openapi.models.Operation;
import org.eclipse.microprofile.openapi.models.parameters.RequestBody;
import org.eclipse.microprofile.openapi.models.media.Content;
import org.eclipse.microprofile.openapi.models.media.MediaType;
import org.eclipse.microprofile.openapi.models.responses.APIResponses;
import org.eclipse.microprofile.openapi.models.responses.APIResponse;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;
import java.util.Map;
import java.util.Set;

function void violationPresenceOfPayload(OpenApiViolationAggregator oas, String errorMessage, String property){
  oas.addViolation("[presenceOfPayload]",
    errorMessage +
    "[Operation: " + property + "]",
    oas.getLineNumber(property));
}

rule "GET/HEAD/DELETE/OPTIONS should have no request payload"
  when
    $api: OpenAPI()
    $operation: Operation() from ApiFunctions.getOperations($api, Set.of(HttpMethod.PATCH, HttpMethod.POST, HttpMethod.PUT))
    $requestBody: RequestBody() from $operation.getRequestBody()
    not RequestBody( $requestBody.getContent() == null )
  then
    violationPresenceOfPayload(oas, "GET/HEAD/DELETE/OPTIONS should have no request payload \t", $operation.getOperationId());
end

rule "HEAD should have no response payload"
  when
    $api: OpenAPI()
    $operation: Operation() from ApiFunctions.getOperations($api, Set.of(HttpMethod.PATCH, HttpMethod.POST, HttpMethod.PUT, HttpMethod.GET, HttpMethod.DELETE, HttpMethod.OPTIONS))
    $responses: APIResponses() from $operation.getResponses()
    $response: APIResponse() from $responses.getAPIResponses().values()
    not APIResponse( $response.getContent() == null )
    $content: Content() from $response.getContent()
    $mediaTypes: Map() from $content.getMediaTypes()
    not Map( $mediaTypes.size() == 0 )
  then
    violationPresenceOfPayload(oas, "HEAD should have no response payload \t", $operation.getOperationId());
end

rule "Status code 200 should have response payload"
  when
    $api: OpenAPI()
    $operation: Operation( $response : /responses/APIResponses/entrySet[key#String == "200"]/value#APIResponse ) from ApiFunctions.getOperations($api, Set.of())
    not (APIResponse(/content/mediaTypes[size != 0]) from $response)
  then
    violationPresenceOfPayload(oas, "Status code 200 should have response payload. Use status code 204 when no payload is provided. \t", $operation.getOperationId());
end

rule "Status code 204 should not have response payload"
  when
    $api: OpenAPI()
    $operation: Operation() from ApiFunctions.getOperations($api, Set.of())
    APIResponses( hasAPIResponse("204") ) from $operation.getResponses()
    Content( $mediaMap : mediaTypes ) from $operation.getResponses().getAPIResponse("204").getContent()
    Map( size != 0 ) from $mediaMap
  then
    violationPresenceOfPayload(oas, "Status code 204 should not have response payload \t", $operation.getOperationId());
end