package be.belgium.gcloud.rest.styleguide.validation.core.rules.oas;

import org.eclipse.microprofile.openapi.models.PathItem.HttpMethod;
import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions;
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;

function void violationDelete(OpenApiViolationAggregator oas, String operationId, String code){
    oas.addViolation("deleteStatusCode"+code, "DELETE operation should not have a status code: "+code,
                     oas.getLineNumber(oas.getLineNumber(operationId), code));
}

//v2
rule "Delete Status Code 201 v2"
	when
		$api: OpenAPI()
		$operationId: String() from ApiFunctions.getOperationId($api, HttpMethod.DELETE, "201")
	then
        violationDelete(oas, $operationId, "201");
end
rule "Delete Status Code 202 v2"
	when
		$api: OpenAPI()
		$operationId: String() from ApiFunctions.getOperationId($api, HttpMethod.DELETE, "202")
	then
        violationDelete(oas, $operationId, "202");
end
rule "Delete Status Code 304 v2"
	when
		$api: OpenAPI()
		$operationId: String() from ApiFunctions.getOperationId($api, HttpMethod.DELETE, "304")
	then
        violationDelete(oas, $operationId, "304");
end
rule "Delete Status Code 413 v2"
	when
		$api: OpenAPI()
		$operationId: String() from ApiFunctions.getOperationId($api, HttpMethod.DELETE, "413")
	then
        violationDelete(oas, $operationId, "413");
end
