package be.belgium.gcloud.rest.styleguide.validation.core.rules.oas;

import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions;
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator
import org.eclipse.microprofile.openapi.models.Operation
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;
import org.eclipse.microprofile.openapi.models.parameters.RequestBody;
import org.eclipse.microprofile.openapi.models.Paths;
import org.eclipse.microprofile.openapi.models.media.Content;
import org.eclipse.microprofile.openapi.models.media.MediaType;
import org.eclipse.microprofile.openapi.models.media.Schema;
import org.eclipse.microprofile.openapi.models.media.Schema.SchemaType;
import org.eclipse.microprofile.openapi.models.responses.APIResponses;
import org.eclipse.microprofile.openapi.models.responses.APIResponse;
import org.apache.http.entity.ContentType
import java.util.List
import java.util.Set;
import java.util.Map.Entry;
import be.belgium.gcloud.rest.styleguide.validation.core.SchemaDefinition;


function Set includeContentTypes() {
  return Set.of("application/json", "multipart/*");
}

function void violationJsonObjectAsTopLevelStructure(OpenApiViolationAggregator oas, SchemaDefinition schema, String operationId, String requestOrResponse, String findAfter){
  oas.addViolation("[evo-object]",
    "In a request or response body, if any, you MUST always return a JSON object (and not e.g. an array) as a top level data structure to support future extensibility. \t"+ operationId + " => " + requestOrResponse + " => " + schema.getParentName() + " => " + schema.getSchema().getType(),
    oas.getLineNumber(oas.getLineNumber(oas.getLineNumber(operationId), findAfter), "schema"));
}

rule "JSON object as top level structure in requestBodies"
  when
    $api: OpenAPI()
    $operation: Operation() from ApiFunctions.getOperations($api)
    $requestBody: RequestBody() from $operation.getRequestBody()
    $content: Content() from $requestBody.getContent()
    $schema: SchemaDefinition() from ApiFunctions.getSchemaFromContent($api, $content, includeContentTypes())
    eval( ApiFunctions.schemaIsExtendedType($api, $schema.getSchema(), SchemaType.OBJECT) == false )
  then
    violationJsonObjectAsTopLevelStructure(oas, $schema, $operation.getOperationId(), "request", "requestBody");
end

rule "JSON object as top level structure in responses"
  when
    $api: OpenAPI()
    $operation: Operation() from ApiFunctions.getOperations($api)
    $responses: APIResponses() from $operation.getResponses()
    $response: Entry() from $responses.getAPIResponses().entrySet()
    $responseValue: APIResponse() from $response.getValue()
    $content: Content() from $responseValue.getContent()
    $schema: SchemaDefinition() from ApiFunctions.getSchemaFromContent($api, $content, includeContentTypes())
    eval( ApiFunctions.schemaIsExtendedType($api, $schema.getSchema(), SchemaType.OBJECT) == false )
  then
    violationJsonObjectAsTopLevelStructure(oas, $schema, $operation.getOperationId(), "response: " + $response.getKey(), $response.getKey().toString());
end