package be.belgium.gcloud.rest.styleguide.validation.core.rules.oas;

import be.belgium.gcloud.rest.styleguide.validation.core.OperationEnum;
import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;

function void violationPut(OpenApiViolationAggregator oas, String operationId, String code){
    oas.addViolation("putStatusCode"+code, "PUT operation should not have a status code: "+code,
                     oas.getLineNumber(oas.getLineNumber(operationId), code));
}

//v2
rule "Put Status Code 202"
	when
		$api: OpenAPI()
		$operationId: String() from ApiFunctions.getOperationId($api, OperationEnum.PUT, "202")
	then
        violationPut(oas, $operationId, "202");
end
rule "Put Status Code 304"
	when
		$api: OpenAPI()
		$operationId: String() from ApiFunctions.getOperationId($api, OperationEnum.PUT, "304")
	then
        violationPut(oas, $operationId, "304");
end
