package be.belgium.gcloud.rest.styleguide.validation.core.rules.oas2;

import java.util.List;
import be.belgium.gcloud.rest.styleguide.validation.core.OperationEnum;
import org.eclipse.microprofile.openapi.models.OpenAPI;
import be.belgium.gcloud.rest.styleguide.validation.core.ApiFunctions;
import be.belgium.gcloud.rest.styleguide.validation.core.jsonpath.ApiPathFunctions;
import be.belgium.gcloud.rest.styleguide.validation.core.jsonpath.OperationData;
import be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator;
global be.belgium.gcloud.rest.styleguide.validation.core.OpenApiViolationAggregator oas;
global java.lang.String jsonString;

function void violationProduce(OpenApiViolationAggregator oas, String operation, String operationId){
    oas.addViolation("defaultMediaTypeProduce",
     "OpenAPI 2.0 specifications SHOULD specify following default media types for produces: 'application/json' and 'application/problem+json'. \t"+ operationId + " ("+operation+")",
      oas.getLineNumber(operationId));
}
function void violationConsume(OpenApiViolationAggregator oas, String operation, String operationId){
    oas.addViolation("defaultMediaTypeConsume",
     "OpenAPI 2.0 specifications SHOULD specify following default media types for consumes: 'application/json'. \t"+ operationId + " ("+operation+")",
      oas.getLineNumber(operationId));
}

// produces
rule "Rule-defaultMediaType-getDontHaveProduces"
    when
        $api: OpenAPI()
        $operationId: String() from ApiPathFunctions.operationIdDontHaveProduce(jsonString, OperationEnum.GET)
    then
        violationProduce(oas,OperationEnum.GET.name(), $operationId);
end

rule "Rule-defaultMediaType-getDontHaveCorrectProduces"
    when
        $api: OpenAPI()
        $operationData: OperationData() from ApiPathFunctions.operationDataDontHaveProduce(jsonString, OperationEnum.GET, ApiPathFunctions.PRODUCES_MEDIATYPE)
    then
        violationProduce(oas, OperationEnum.GET.name(), $operationData.getOperationId());
end

rule "Rule-defaultMediaType-posttDontHaveCorrectProduces"
    when
        $api: OpenAPI()
        $operationData: OperationData() from ApiPathFunctions.operationDataDontHaveProduce(jsonString, OperationEnum.POST, ApiPathFunctions.PRODUCES_MEDIATYPE)
    then
        violationProduce(oas, OperationEnum.POST.name(), $operationData.getOperationId());
end

rule "Rule-defaultMediaType-putDontHaveCorrectProduces"
    when
        $api: OpenAPI()
        $operationData: OperationData() from ApiPathFunctions.operationDataDontHaveProduce(jsonString, OperationEnum.PUT, ApiPathFunctions.PRODUCES_MEDIATYPE)
    then
        violationProduce(oas, OperationEnum.PUT.name(), $operationData.getOperationId());
end

rule "Rule-defaultMediaType-patchDontHaveCorrectProduces"
    when
        $api: OpenAPI()
        $operationData: OperationData() from ApiPathFunctions.operationDataDontHaveProduce(jsonString, OperationEnum.PATCH, ApiPathFunctions.PRODUCES_MEDIATYPE)
    then
        violationProduce(oas, OperationEnum.PATCH.name(), $operationData.getOperationId());
end

rule "Rule-defaultMediaType-optionsDontHaveCorrectProduces"
    when
        $api: OpenAPI()
        $operationData: OperationData() from ApiPathFunctions.operationDataDontHaveProduce(jsonString, OperationEnum.OPTIONS, ApiPathFunctions.PRODUCES_MEDIATYPE)
    then
        violationProduce(oas, OperationEnum.OPTIONS.name(), $operationData.getOperationId());
end

// consumes
rule "Rule-defaultMediaType-postDontHaveConsumes"
    when
        $api: OpenAPI()
        $operationId: String() from ApiPathFunctions.operationIdDontHaveConsume(jsonString, OperationEnum.POST)
    then
        violationConsume(oas, OperationEnum.POST.name(), $operationId);
end
rule "Rule-defaultMediaType-postDontHaveCorrectConsumes"
    when
        $api: OpenAPI()
        $operationData: OperationData() from ApiPathFunctions.operationDataDontHaveConsume(jsonString, OperationEnum.POST, ApiPathFunctions.CONSUMES_MEDIATYPE)
    then
        violationConsume(oas, OperationEnum.POST.name(), $operationData.getOperationId());
end

rule "Rule-defaultMediaType-putDontHaveConsumes"
    when
        $api: OpenAPI()
        $operationId: String() from ApiPathFunctions.operationIdDontHaveConsume(jsonString, OperationEnum.PUT)
    then
        violationConsume(oas, OperationEnum.PUT.name(), $operationId);
end
rule "Rule-defaultMediaType-putDontHaveCorrectConsumes"
    when
        $api: OpenAPI()
        $operationData: OperationData() from ApiPathFunctions.operationDataDontHaveConsume(jsonString, OperationEnum.PUT, ApiPathFunctions.CONSUMES_MEDIATYPE)
    then
        violationConsume(oas, OperationEnum.PUT.name(), $operationData.getOperationId());
end

rule "Rule-defaultMediaType-patchDontHaveConsumes"
    when
        $api: OpenAPI()
        $operationId: String() from ApiPathFunctions.operationIdDontHaveConsume(jsonString, OperationEnum.PATCH)
    then
        violationConsume(oas, OperationEnum.PATCH.name(), $operationId);
end
rule "Rule-defaultMediaType-patchDontHaveCorrectConsumes"
    when
        $api: OpenAPI()
        $operationData: OperationData() from ApiPathFunctions.operationDataDontHaveConsume(jsonString, OperationEnum.PATCH, ApiPathFunctions.CONSUMES_MEDIATYPE)
    then
        violationConsume(oas, OperationEnum.PATCH.name(), $operationData.getOperationId());
end