openapi: 3.0.0
info:
  title: Address schemas
  version: "1.0"
paths: {}
components:
  schemas:
    Address:
      description: An address
      type: object
      properties:
        street:
          $ref: '#/components/schemas/Street'
        houseNumber:
          type: string
        boxNumber:
          type: string
        postCode:
          type: string
        municipality:
          $ref: '#/components/schemas/Municipality'
        belgianRegionCode:
          $ref: 'belgif/location/v1/location-v1.yaml#/components/schemas/BelgianRegionCode'
        country:
          $ref: '#/components/schemas/Country'
      required:
        - street
        - municipality
        - houseNumber
        - postCode
    Country:
      type: object
      properties:
        countryNisCode:
          $ref: 'belgif/location/v1/location-v1.yaml#/components/schemas/CountryNisCode'
        name:
          type: string
      required:
        - countryNisCode
    Municipality:
      type: object
      properties:
        name:
          type: string
        code:
          $ref: 'belgif/location/v1/location-v1.yaml#/components/schemas/MunicipalityCode'
      required: [name]
    Street:
        type: object
        properties:
          name:
            type: string
          rrnCode:
            $ref: 'belgif/location/v1/location-v1.yaml#/components/schemas/StreetRrnCode'
        required: [name]