package io.github.belgif.rest.guide.validator.rules.oas;

import org.eclipse.microprofile.openapi.models.PathItem.HttpMethod;
import org.eclipse.microprofile.openapi.models.OpenAPI;
import io.github.belgif.rest.guide.validator.core.ApiFunctions;
import io.github.belgif.rest.guide.validator.core.ViolationReport;
import io.github.belgif.rest.guide.validator.core.model.OperationDefinition;
import org.eclipse.microprofile.openapi.models.Operation;
import org.eclipse.microprofile.openapi.models.responses.APIResponses;
import org.eclipse.microprofile.openapi.models.responses.APIResponse;
import java.util.Set;

global io.github.belgif.rest.guide.validator.core.ViolationReport oas;

function void violationGet(ViolationReport oas, OperationDefinition operation, String code){
    oas.addViolation("[stat-codes]", "GET operation should not have this status code", "[statuscode: " + code + "]",
                     operation);
}

rule "Get Status Code 201 v3"
	when
		$operation: OperationDefinition( method == HttpMethod.GET)
		OperationDefinition($response: /model/responses/APIResponses[keySet contains "201"]) from $operation
	then
        violationGet(oas, $operation, "201");
end
rule "Get Status Code 202 v3"
	when
		$operation: OperationDefinition( method == HttpMethod.GET)
		OperationDefinition($response: /model/responses/APIResponses[keySet contains "202"]) from $operation
	then
        violationGet(oas, $operation, "202");
end
rule "Get Status Code 204 v3"
	when
		$operation: OperationDefinition( method == HttpMethod.GET)
		OperationDefinition($response: /model/responses/APIResponses[keySet contains "204"]) from $operation
	then
        violationGet(oas, $operation, "204");
end
rule "Get Status Code 409 v3"
	when
		$operation: OperationDefinition( method == HttpMethod.GET)
		OperationDefinition($response: /model/responses/APIResponses[keySet contains "409"]) from $operation
	then
        violationGet(oas, $operation, "409");
end
rule "Get Status Code 412 v3"
	when
		$operation: OperationDefinition( method == HttpMethod.GET)
		OperationDefinition($response: /model/responses/APIResponses[keySet contains "412"]) from $operation
	then
        violationGet(oas, $operation, "412");
end
rule "Get Status Code 413 v3"
	when
		$operation: OperationDefinition( method == HttpMethod.GET)
		OperationDefinition($response: /model/responses/APIResponses[keySet contains "413"]) from $operation
	then
        violationGet(oas, $operation, "413");
end