# Maven CI build for the belgif openapi projects
name: openapi-maven-ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#    - uses: actions/checkout@v4
#    - name: Set up Adopt OpenJDK 17
#      uses: actions/setup-java@v4
#      with:
#        distribution: adopt
#        java-version: '17'
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.14.0
      with:
        java-version: '17'
        java-distribution: 'adopt'
        maven-version: '3.9.9'
    - name: Build with Maven
      run: mvn -B verify