# Maven CI build for the belgif openapi projects
name: openapi-maven-ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: [ '3.8.5', '3.9.9' ]

    steps:
#    Setup Maven action to specify maven version > required for BUG https://issues.apache.org/jira/browse/MNG-7055
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.18.0
      with:
        java-version: '17'
        java-distribution: 'adopt'
        maven-version: ${{ matrix.maven }}
        cache-enabled: 'false'
    - name: Build with Maven
      run: mvn -B verify