# Release belgif openapi projects to Maven Central when a version tag is created
name: openapi-maven-release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Adopt OpenJDK 17
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: '17'
        server-id: ossrh
        server-username: MAVEN_CENTRAL_USER
        server-password: MAVEN_CENTRAL_TOKEN
    - name: Build with Maven
      run: mvn -B deploy -Drevision=${GITHUB_REF_NAME:1} -Prelease
      env:
        MAVEN_GPG_KEY: ${{ secrets.OPENAPI_OSSRH_GPG_SECRET_KEY }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OPENAPI_OSSRH_GPG_SECRET_KEY_PASSWORD }}
        MAVEN_CENTRAL_USER: ${{ secrets.OPENAPI_OSSRH_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.OPENAPI_OSSRH_TOKEN }}
    - name: Create GitHub release
      run: |
        gh release create ${GITHUB_REF} --draft --title "Release ${GITHUB_REF_NAME}" --notes "Changes:
        - [placeholder]"